### ISSUE TITLE
Implement Translations for Android App in English

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revolutionary_Farmers#9]
Add English translations to the Android app to ensure it is fully localized for English-speaking users.

**TASKS:**

## 1.	Translation File Setup:
	•	Create or update the strings.xml file in the res/values-en directory.
	•	Ensure all UI text, error messages, and button labels are translated.
## 2.	UI Implementation:
	•	Verify that all elements, including notifications, tooltips, and dialog boxes, are properly localized.
	•	Ensure the app switches to the correct language based on user preference or device settings.
## 3.	Dynamic Content Handling:
	•	Ensure dynamic content like error messages, alerts, and pop-ups are also translated and updated accordingly.
## 4.	Testing:
	•	Test the app’s functionality with the English language selected to confirm proper translations.
	•	Validate that the layout adapts correctly for English text, especially in terms of text direction or length.
## 5.	Consistency Check:
	•	Review the app for any untranslated text or inconsistencies between languages.

Expected Outcome:

The app should be fully translated into English, providing a seamless user experience for English-speaking users.

**Comment by SYLVIANNORUKA** [comment]
Is this issue still available?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by caxtonacollins** [comment]
Can I start working on this?

**Comment by ShantelPeters** [comment]
Can I handle this task?

**Comment by jancris100** [comment]
Would love to tackle this! I'm from dojo coding I have 2 years of experience as full stack developer and also Im actually work as mobile developer with figma on MAUI I'm used the resources to implement the transactions

**Comment by KevinMB0220** [comment]
Hola mi nombre es Kevin, soy miembro de Dojo Coding, tengo experiencia en desarrollo web y ya he colaborado en otros proyectos de desarrollo web

I would start by adding all the translations to the strings.xml file in the res/values-en directory, covering UI text, error messages, and dynamic content. Then, I’d test the app with English selected to ensure everything displays correctly and fits well in the layout. Finally, I’d double-check for any untranslated text or inconsistencies to make sure the app feels seamless for English-speaking users.

**Comment by pablomadrigal** [comment]
# I'm Pablo Madrigal. 
## I'm a Fullstack Developer with experience on Android and also part of Dojo Coding 🔥

## Problem
Implement Translations for Android App in English

## Solution
Edit the strings.xml file in the res/values-en directory.
Modify all the current strings to accept the translation to English and have in the future, the option to translate to other languages.

I'm going to test all the application in both languages and change language in the middle of the testing to ensure all the scenarios are ready for the final user, also testing dynamic content like pop-ups and messages

**Comment by sebas11042** [comment]
I am an advanced computer science student with experience in Java, JavaScript, Unity, and application development. I am currently part of SunsetLabs, where I contribute to creating functional and intuitive interfaces for innovative projects. My experience includes asset management, frontend development, and designing efficient UI systems. These skills enable me to tackle localization projects in Android applications, ensuring precise implementation and a seamless user experience.

I will resolve this issue by creating a dedicated strings.xml file for English translations in the res/values-en directory. I will identify and migrate all hardcoded text in the application to the resource file to ensure full localization. Additionally, I will adjust dynamic interface elements to retrieve text directly from the localized resources. I will conduct thorough testing to verify that English text loads correctly and address any design issues caused by text length. Finally, I will validate that all translations are consistent and complete before documenting and finalizing the task.

**Comment by salazarsebas** [comment]
Assigned @sebas11042 ! ⛩️
Feel free to work on the issue. 🚀

**Comment by alfatektecnologia** [comment]
Hi there,

I´d appreciate an opportunity to contribute.

Best,

Emanoel
